apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: max-lbservice
spec:
  crd:
    spec:
      names:
        kind: max-lbservice
      validation:
        # Schema for the `parameters` field
        openAPIV3Schema:
          properties:
            maxlbs:
              type: string
              description: the maximum number of service type LoadBalancer allowed
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package maxlbservice
        violation[{"msg": msg}] {
          input.review.kind.kind = "Service"
          input.review.kind.group == ""
          input.review.object.spec.type = "LoadBalancer"
          lbcount := count(lbs)
          lbcount >= to_number(input.parameters.maxlbs)
          msg := sprintf("LoadBalancer Services are current at max capacity of %v",[input.parameters.maxlbs])
        }
        lbs[{"name": name}] { 
          service := data.inventory.namespace[namespace][_]["Service"][sname]
          service.spec.type == "LoadBalancer"
          name := service
        }